# Generated by Django 5.0.6 on 2024-05-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WallPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('url', models.ImageField(upload_to='wallpaper/', verbose_name='路径')),
                ('author', models.CharField(default='余天王', max_length=128, verbose_name='作者')),
                ('detail', models.TextField(default='详情描述空空如也', verbose_name='详情')),
            ],
        ),
    ]
