# Generated by Django 5.0.6 on 2024-05-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, verbose_name='ip地址')),
                ('times', models.IntegerField(default=100, verbose_name='剩余次数(默认一百次)')),
            ],
        ),
    ]
