# Generated by Django 5.0.6 on 2024-05-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_iplist'),
    ]

    operations = [
        migrations.CreateModel(
            name='YtwKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='ytw_key')),
                ('times', models.IntegerField(default=300, verbose_name='剩余次数')),
            ],
        ),
    ]
